### ISSUE TITLE
Tabs & Icon changes

### ISSUE THREAD

**Issue by mrlensmith** [mrlensmith/paseoGO#11]
1. Can the images on the tabs (upper right) be larger?
2. Can the tabs be set to group at a smaller resolution (If medium now can it be changed to small)? Currently, they are set to group at ~tablet resolution but there is plenty of room to keep them.
3. When the tabs do group and you expand the hamburger menu, we only see the icons but no text. Can text be added when the tabs are grouped?

**Comment by miasiam** [comment]
Icons can be larger however there was an issue on font awesome when I originally tried to. I will check if it is resolved. The tabs are through bootstrap, as far as I know I can add text beside the logo but I'm not sure if I can add text under the logo.  I will try to see if I can make them smaller for the hamburger menu.
