### ISSUE TITLE
Search page stacking

### ISSUE THREAD

**Issue by mrlensmith** [mrlensmith/paseoGO#13]
Can the sections on the search page stack below 768 px instead of ~568 px? I think the extra room will make the page look better once we get the data on it.

Also, can white space be added between the sections so they are not touching (at any resolution)?

**Comment by miasiam** [comment]
I can add white space between the divs so they are not touching and also fix the responsive pixels as well. I will try to add spacing on the bottom of the page and see what I can do about the search page stack px.
